# Generated by Django 4.2.16 on 2024-12-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0003_about_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
